version: 2.1 
jobs:
  run-build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
    - run:
         name: Install Dependencies
         command: |
         echo "Installing Salesforce CLI"
        sudo npm install -global sfdx-cli
    - run:
         name: Authorize Target Deployment Org
         command: |
           mkdir keys
          echo $Server_Key | base64 -di > keys/server.key

          echo "Authenticating org"
          sfdx force:auth:jwt:grant --clientid $Consumer_key --jwtkeyfile keys/server.key --username $SFDX_Username --setdefaultdevhubusername -a DevHub
      - run:
          name: convert the files in deploy folder to MDAPI format
          command: |
            #from SFDX project structure CONVERT TO MDAPI format
            sfdx force:source:convert -r deploy -d deploy-sf-metadata     
      - run:
          name: MDAPI Deploy to Target Deployment Org
          no_output_timeout: 300m
          command: |
            #Deploy to target deployment org and run unit tests. 
            sfdx force:mdapi:deploy --checkonly --wait -1 -d deploy-sf-metadata --targetusername $SFDX_Username --testlevel $TESTLEVEL -r $TESTCLASSLIST            
workflows:
  version: 2
  validate:
    jobs:
      - run-build
      